# Generated by Django 2.0.3 on 2018-03-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month1', models.FloatField()),
                ('month2', models.FloatField()),
                ('month3', models.FloatField()),
                ('month4', models.FloatField()),
                ('month5', models.FloatField()),
                ('month6', models.FloatField()),
                ('month7', models.FloatField()),
                ('month8', models.FloatField()),
                ('month9', models.FloatField()),
                ('month10', models.FloatField()),
                ('month11', models.FloatField()),
                ('month12', models.FloatField()),
                ('winter', models.FloatField()),
                ('spring', models.FloatField()),
                ('autumn', models.FloatField()),
                ('summer', models.FloatField()),
                ('annual', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('max_temp', models.CharField(max_length=1)),
                ('mean_temp', models.CharField(max_length=1)),
                ('rainfall', models.CharField(max_length=1)),
                ('sunshine', models.CharField(max_length=1)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Area_desc')),
            ],
        ),
        migrations.RemoveField(
            model_name='temperatures',
            name='area',
        ),
        migrations.DeleteModel(
            name='Temperatures',
        ),
    ]
